-- MySQL Script generated by MySQL Workbench
-- 10/27/14 09:31:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema skilltest_prg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema skilltest_prg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `skilltest_prg` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `skilltest_prg` ;

-- -----------------------------------------------------
-- Table `skilltest_prg`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skilltest_prg`.`members` (
  `id_member` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `address` VARCHAR(100) NULL,
  `is_active` ENUM('active','inactive') NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id_member`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skilltest_prg`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skilltest_prg`.`books` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `isbn` VARCHAR(45) NULL,
  `published` INT NULL,
  `is_active` ENUM('active','inactive') NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id_book`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skilltest_prg`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skilltest_prg`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(15) NULL,
  `password` VARCHAR(32) NULL,
  -- `salt` VARCHAR(5) NULL,
  `is_active` ENUM('active','inactive') NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `skilltest_prg`.`books_outs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skilltest_prg`.`books_outs` (
  `id_books_out` INT NOT NULL AUTO_INCREMENT,
  `id_member` INT NOT NULL,
  `id_book` INT NOT NULL,
  `date_out` DATE NULL,
  `date_in` DATE NULL,
  `date_in_actual` DATE NULL,
  `id_user` INT NOT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id_books_out`),
  INDEX `fk_book_outs_members_idx` (`id_member` ASC),
  INDEX `fk_book_outs_books1_idx` (`id_book` ASC),
  INDEX `fk_book_outs_users1_idx` (`id_user` ASC),
  CONSTRAINT `fk_book_outs_members`
    FOREIGN KEY (`id_member`)
    REFERENCES `skilltest_prg`.`members` (`id_member`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_outs_books1`
    FOREIGN KEY (`id_book`)
    REFERENCES `skilltest_prg`.`books` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_outs_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `skilltest_prg`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
